---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - mkdir -p $DEPLOYPATH/addis
    - /bin/cp MulatAddis-*.* $DEPLOYPATH/addis
    - /bin/cp README.md $DEPLOYPATH/addis
    - zip addis.zip $DEPLOYPATH/addis/*
    - /bin/mv addis.zip $DEPLOYPATH/addis
    - echo "....finished....."