---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - export NAME=addis
    - mkdir -p $DEPLOYPATH/$NAME
    - /bin/cp MulatAddis-*.* $DEPLOYPATH/$NAME
    - /bin/cp README.md $DEPLOYPATH/$NAME
    - zip addis.zip $DEPLOYPATH/$NAME/*
    - mv -mj addis.zip $DEPLOYPATH/$NAME
    - echo "....finished, addis........"